//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }

    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""8f397f47-d310-4679-ad71-3f472c0fb5cb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6838bf5b-d781-4388-9c07-4693d4e2ca48"",
                    ""expectedControlType"": ""Vector2"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""45ebb3c3-7009-4a8a-a165-ed3054c6ef36""
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""2e782fbb-135a-4a43-9a9c-3a4373d3a8e2""
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""0478b12f-c9a9-4cdf-9371-1860496b3f36""
                },
                {
                    ""name"": ""Craft"",
                    ""type"": ""Button"",
                    ""id"": ""9494e607-349a-4168-ab04-e72ea9023cea""
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""e12ea45d-86cc-4953-ba85-4ebaeae503c7""
                },
                {
                    ""name"": ""Weapon1"",
                    ""type"": ""Button"",
                    ""id"": ""bd8cb524-a4ea-4b32-a89c-9e0c346146f5""
                },
                {
                    ""name"": ""Weapon2"",
                    ""type"": ""Button"",
                    ""id"": ""5ff2da64-dee7-4e5a-b8de-28f8fd9c52aa""
                },
                {
                    ""name"": ""Weapon3"",
                    ""type"": ""Button"",
                    ""id"": ""d6fa25ab-88a4-46b7-8d0f-406c7777892b""
                },
                {
                    ""name"": ""Melee"",
                    ""type"": ""Button"",
                    ""id"": ""9e876173-9b95-4a4d-8e4b-7b5fe2f0b698""
                },
                {
                    ""name"": ""ADS"",
                    ""type"": ""Button"",
                    ""id"": ""d331dae3-a933-4df8-8e65-bf621e691d2b""
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""ee3c41dc-3226-4ae6-9f6e-b0183f861302""
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3383b4d5-fc66-4647-b928-edca3a4ab878"",
                    ""path"": ""2DVector"",
                    ""action"": ""Move"",
                    ""isComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3f85a2d0-ad06-4bac-ba2a-5e0f545d0f67"",
                    ""path"": ""<Keyboard>/w"",
                    ""action"": ""Move"",
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fdbdac5d-42b4-4401-b681-5f8d2388d38c"",
                    ""path"": ""<Keyboard>/s"",
                    ""action"": ""Move"",
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a8ca0c47-50f5-4c89-9770-def1d77ab876"",
                    ""path"": ""<Keyboard>/a"",
                    ""action"": ""Move"",
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1256667d-c507-4ca0-a048-8de1d8f721a6"",
                    ""path"": ""<Keyboard>/d"",
                    ""action"": ""Move"",
                    ""isPartOfComposite"": true
                },
                {
                    ""id"": ""11824abd-e6f1-4acd-8663-22360e3afdb9"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""action"": ""Sprint""
                },
                {
                    ""id"": ""5e4270dd-d5d7-4faa-b7a3-2e7b7fb7755f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""action"": ""Map""
                },
                {
                    ""id"": ""a6b2b1a2-254c-470f-9a1f-438a10109095"",
                    ""path"": ""<Keyboard>/i"",
                    ""action"": ""Inventory""
                },
                {
                    ""id"": ""fcb1ac19-edbc-48ad-a882-268972a2f710"",
                    ""path"": ""<Keyboard>/c"",
                    ""action"": ""Craft""
                },
                {
                    ""id"": ""071bb287-198d-43f5-9cba-ac00b998e654"",
                    ""path"": ""<Keyboard>/r"",
                    ""action"": ""Reload""
                },
                {
                    ""id"": ""5cb54c6f-bee0-4a12-9812-255054c1d0e7"",
                    ""path"": ""<Keyboard>/1"",
                    ""action"": ""Weapon1""
                },
                {
                    ""id"": ""e895afd1-acf8-44e9-b378-6dbc6f08d394"",
                    ""path"": ""<Keyboard>/2"",
                    ""action"": ""Weapon2""
                },
                {
                    ""id"": ""8276c639-0d9a-4c5a-ba7d-25ec9c984962"",
                    ""path"": ""<Keyboard>/3"",
                    ""action"": ""Weapon3""
                },
                {
                    ""id"": ""849fcd24-a8b8-49a6-b295-2c30cef31f0e"",
                    ""path"": ""<Keyboard>/f"",
                    ""action"": ""Melee""
                },
                {
                    ""id"": ""ef95c1f0-8bca-4cc9-8c2a-2904293a2bed"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""action"": ""ADS""
                },
                {
                    ""id"": ""f4e31db3-7d28-4bb5-91ae-7bc9ef26baf8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""action"": ""Escape""
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Sprint = m_Gameplay.FindAction("Sprint", throwIfNotFound: true);
        m_Gameplay_Map = m_Gameplay.FindAction("Map", throwIfNotFound: true);
        m_Gameplay_Inventory = m_Gameplay.FindAction("Inventory", throwIfNotFound: true);
        m_Gameplay_Craft = m_Gameplay.FindAction("Craft", throwIfNotFound: true);
        m_Gameplay_Reload = m_Gameplay.FindAction("Reload", throwIfNotFound: true);
        m_Gameplay_Weapon1 = m_Gameplay.FindAction("Weapon1", throwIfNotFound: true);
        m_Gameplay_Weapon2 = m_Gameplay.FindAction("Weapon2", throwIfNotFound: true);
        m_Gameplay_Weapon3 = m_Gameplay.FindAction("Weapon3", throwIfNotFound: true);
        m_Gameplay_Melee = m_Gameplay.FindAction("Melee", throwIfNotFound: true);
        m_Gameplay_ADS = m_Gameplay.FindAction("ADS", throwIfNotFound: true);
        m_Gameplay_Escape = m_Gameplay.FindAction("Escape", throwIfNotFound: true);
    }

    ~PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_Gameplay.enabled,
            "This will cause a leak. PlayerControls.Gameplay.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Sprint;
    private readonly InputAction m_Gameplay_Map;
    private readonly InputAction m_Gameplay_Inventory;
    private readonly InputAction m_Gameplay_Craft;
    private readonly InputAction m_Gameplay_Reload;
    private readonly InputAction m_Gameplay_Weapon1;
    private readonly InputAction m_Gameplay_Weapon2;
    private readonly InputAction m_Gameplay_Weapon3;
    private readonly InputAction m_Gameplay_Melee;
    private readonly InputAction m_Gameplay_ADS;
    private readonly InputAction m_Gameplay_Escape;

    public struct GameplayActions
    {
        private PlayerControls m_Wrapper;

        public GameplayActions(PlayerControls wrapper) { m_Wrapper = wrapper; }

        public InputAction Move => m_Wrapper.m_Gameplay_Move;
        public InputAction Sprint => m_Wrapper.m_Gameplay_Sprint;
        public InputAction Map => m_Wrapper.m_Gameplay_Map;
        public InputAction Inventory => m_Wrapper.m_Gameplay_Inventory;
        public InputAction Craft => m_Wrapper.m_Gameplay_Craft;
        public InputAction Reload => m_Wrapper.m_Gameplay_Reload;
        public InputAction Weapon1 => m_Wrapper.m_Gameplay_Weapon1;
        public InputAction Weapon2 => m_Wrapper.m_Gameplay_Weapon2;
        public InputAction Weapon3 => m_Wrapper.m_Gameplay_Weapon3;
        public InputAction Melee => m_Wrapper.m_Gameplay_Melee;
        public InputAction ADS => m_Wrapper.m_Gameplay_ADS;
        public InputAction Escape => m_Wrapper.m_Gameplay_Escape;

        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }

        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }

        public bool enabled => Get().enabled;

        public static implicit operator InputActionMap(GameplayActions set)
        {
            return set.Get();
        }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance))
                return;

            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);

            Move.started += instance.OnMove;
            Move.performed += instance.OnMove;
            Move.canceled += instance.OnMove;

            Sprint.started += instance.OnSprint;
            Sprint.performed += instance.OnSprint;
            Sprint.canceled += instance.OnSprint;

            Map.started += instance.OnMap;
            Map.performed += instance.OnMap;
            Map.canceled += instance.OnMap;

            Inventory.started += instance.OnInventory;
            Inventory.performed += instance.OnInventory;
            Inventory.canceled += instance.OnInventory;

            Craft.started += instance.OnCraft;
            Craft.performed += instance.OnCraft;
            Craft.canceled += instance.OnCraft;

            Reload.started += instance.OnReload;
            Reload.performed += instance.OnReload;
            Reload.canceled += instance.OnReload;

            Weapon1.started += instance.OnWeapon1;
            Weapon1.performed += instance.OnWeapon1;
            Weapon1.canceled += instance.OnWeapon1;

            Weapon2.started += instance.OnWeapon2;
            Weapon2.performed += instance.OnWeapon2;
            Weapon2.canceled += instance.OnWeapon2;

            Weapon3.started += instance.OnWeapon3;
            Weapon3.performed += instance.OnWeapon3;
            Weapon3.canceled += instance.OnWeapon3;

            Melee.started += instance.OnMelee;
            Melee.performed += instance.OnMelee;
            Melee.canceled += instance.OnMelee;

            ADS.started += instance.OnADS;
            ADS.performed += instance.OnADS;
            ADS.canceled += instance.OnADS;

            Escape.started += instance.OnEscape;
            Escape.performed += instance.OnEscape;
            Escape.canceled += instance.OnEscape;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (!m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                return;

            Move.started -= instance.OnMove;
            Move.performed -= instance.OnMove;
            Move.canceled -= instance.OnMove;

            Sprint.started -= instance.OnSprint;
            Sprint.performed -= instance.OnSprint;
            Sprint.canceled -= instance.OnSprint;

            Map.started -= instance.OnMap;
            Map.performed -= instance.OnMap;
            Map.canceled -= instance.OnMap;

            Inventory.started -= instance.OnInventory;
            Inventory.performed -= instance.OnInventory;
            Inventory.canceled -= instance.OnInventory;

            Craft.started -= instance.OnCraft;
            Craft.performed -= instance.OnCraft;
            Craft.canceled -= instance.OnCraft;

            Reload.started -= instance.OnReload;
            Reload.performed -= instance.OnReload;
            Reload.canceled -= instance.OnReload;

            Weapon1.started -= instance.OnWeapon1;
            Weapon1.performed -= instance.OnWeapon1;
            Weapon1.canceled -= instance.OnWeapon1;

            Weapon2.started -= instance.OnWeapon2;
            Weapon2.performed -= instance.OnWeapon2;
            Weapon2.canceled -= instance.OnWeapon2;

            Weapon3.started -= instance.OnWeapon3;
            Weapon3.performed -= instance.OnWeapon3;
            Weapon3.canceled -= instance.OnWeapon3;

            Melee.started -= instance.OnMelee;
            Melee.performed -= instance.OnMelee;
            Melee.canceled -= instance.OnMelee;

            ADS.started -= instance.OnADS;
            ADS.performed -= instance.OnADS;
            ADS.canceled -= instance.OnADS;

            Escape.started -= instance.OnEscape;
            Escape.performed -= instance.OnEscape;
            Escape.canceled -= instance.OnEscape;
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var existing in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                RemoveCallbacks(existing);

            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }

    public GameplayActions Gameplay => new GameplayActions(this);

    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnCraft(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnWeapon1(InputAction.CallbackContext context);
        void OnWeapon2(InputAction.CallbackContext context);
        void OnWeapon3(InputAction.CallbackContext context);
        void OnMelee(InputAction.CallbackContext context);
        void OnADS(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
}
